### ISSUE TITLE
2 tabs Files/Projects

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_favorites#10]
Для Куд можно задать
ext_prj = '.cuda-proj'
для Син
ext_prj = '.synw-proj'
Wish: файлы с расширением ext_prj показывать в табе Projects. Не такие в первом табе Files. Было удобно иметь 2 таба files/projects. Если файлов больше 20 и проектов 10

**Comment by kvichans** [comment]
Сейчас табы в диалоге "куцые" - я знаю только реализацию через checkbutton (см. в FiF Help:[Tips, Keys, ...])
В таком виде ими пользоваться не приятно.

Есть другие идеи?

**Comment by Alexey-T** [comment]
думаю, нет, сорри..

**Comment by Alexey-T** [comment]
Можно потом добавить "type=tabs" ..

![pag](https://cloud.githubusercontent.com/assets/4154978/16249131/0759229c-3825-11e6-953b-cfafd1b05f84.png)

**Comment by kvichans** [comment]
Новый контрол - это хорошо. По использованию он будет похож на listbox

**Comment by kvichans** [comment]
Правильно я понимаю, что пока в Син не появится checkbutton или tabs _табы_ не показать?

**Comment by Alexey-T** [comment]
ну да. Tabs появится скоро

**Comment by kvichans** [comment]
Планирую сделать не два таба, а много - под нужды пользователя

**Comment by Alexey-T** [comment]
Beta upload, /bb/
