### ISSUE TITLE
Wish: char prefix of listbox

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_favorites#11]
Listbox in SW: имеет символ префикс.
элементы первые- символы 1..0
потом- символы A..Z
потом пробелы

http://synwrite.sourceforge.net/forums/viewtopic.php?p=9915#p9915

**Comment by kvichans** [comment]
Отображение номеров - это осмысленно только если есть способ им пользоваться.
Цифры можно сделать _горячими_ через невидимые кнопки. В FiF так несколько доп.ускорителей (Alt+1, Alt+2,...) реализованы.
А вот буквы не получится - они будут накладываться на ускорители видимых кнопок.

Итого: добавлю цифры. 
То есть первые десять элементов можно будет вызвать через
Alt+1, Alt+2,..., Alt+0

**Comment by Alexey-T** [comment]
Я сделал так в https://github.com/Alexey-T/cuda_favorites/commit/1cca66aaf7b3218c95628133e2da9326e66ce6cb
Linux: цифры и буквы делают focus

**Comment by kvichans** [comment]
Не понял про "делают фокус". Смещают каретку? Да это тоже пригодится.

**Comment by Alexey-T** [comment]
смещают каретку, индекс.
