### ISSUE TITLE
bt Demo tabs

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_favorites#14]
Это не рабочий, а DEMO вариант. Он для тестирования нового контрола tabs.
![fav-tabs](https://cloud.githubusercontent.com/assets/7419630/16304037/58094338-395c-11e6-846b-1697045a473b.PNG)
1) Обе вкладки живые, их можно наполнять и использовать
2) Название второй вкладки `Projects` пока не имеет отношения ни к каким проектам.
3) Ускорители в именах ярлыков не работают

**Comment by Alexey-T** [comment]
Благодарю,потестю в лин

**Comment by Alexey-T** [comment]
- files tab, 1 файл
- proj tab. добавил 2 файла. Выделил ф1, потом ф2. 
- клик files
- плаг закрылся (ош-к нет)

**Comment by Alexey-T** [comment]
Small size-y

![smal](https://cloud.githubusercontent.com/assets/4154978/16305173/b6168e92-3969-11e6-98e6-87e729afbcb2.png)

**Comment by kvichans** [comment]
1) Потестирую
2) Small size-y. Попробуйте заменить на 
`dict(cid='tabs',tp='tabs' ,t=3,h=27`

**Comment by kvichans** [comment]
1) 2) fix

**Comment by Alexey-T** [comment]
Закроете?
