### ISSUE TITLE
[beta] Store folders

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_favorites#18]
1. У кнопки `Add...` изменился тултип
![image](https://user-images.githubusercontent.com/7419630/51664055-8ca4aa00-1fc9-11e9-9c02-7eccbe077c91.png)
2. При клике с `Shift` появляется диалог выбора папки
3. В списке имена папок отображаются в скобках `[` `]`
4. Объекты, которых нет, теперь отображаются с префиксом `? `
5. По кнопке `Open` на папке появляется запрос файла в этой папке

**Comment by Alexey-T** [comment]
запостил на руборд. спасибо.

**Comment by Alexey-T** [comment]
переведу для history-

+ add: button "Add" has changed caption, Shift+click allows to add folders to Fav list
+ add: folders in the list are marked by [ ] brackets
+ add: non existing items in the list are marked by ?
+ add: button "Open" on a folder - suggests to open file in this folder

**Comment by kvichans** [comment]
ок
поправлю историю и опубликую

**Comment by Alexey-T** [comment]
закроем?
