### ISSUE TITLE
fix needed

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_favorites#22]
FROM_API_VERSION= '1.0.146'

мусор
 
def get_fav_data():
    return json.loads(open(fav_json).read(), object_pairs_hook=OrdDict) \
      

 говорили же про _json_loads

**Comment by kvichans** [comment]
Вы с кем-то "говорили"? Со мной никакого договора не было.

**Comment by Alexey-T** [comment]
Ok
