### ISSUE TITLE
Donot use "dlg_wrapper"

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_favorites#4]
For Synw usage, do not use dlg_wrapper, and appx

**Comment by kvichans** [comment]
Это как?
1. Чем dlg_wrapper не годен?
2. cudax_lib уже не используется.

**Comment by Alexey-T** [comment]
1-Его портировать  на син трудно

**Comment by kvichans** [comment]
1. Это же не ваша забота. Когда дойдут руки, я разберусь в чем разница в реализациях dlg_custom в Син и Куд. И адаптирую dlg_wrapper
